package es.tiernoparla.thewitcher.modelo.FicheroMock

import es.tiernoparla.thewitcher.modelo.Personaje

/**
 * Esta clase simulará el leer un fichero que proveera de infromacion a la base de datos
 * En un entorno mas realista el fichero debe ser manejado por el viewModel, este
 * manejará sus datos entre el fichero y la base de datos
 * @author jhony
 */
class FicheroMock {
    private val listaPersonajes: MutableList<Personaje> = mutableListOf<Personaje>()

    constructor(){
        cargarLista()
    }
    fun cargarLista(){
        val p1: Personaje= Personaje("Geralt de Rivia","Brujo", "","Podría contar muchas cosas sobre ese famoso cazador de monstruos, el hombre conocido en Idioma Antiguo como Gwynbleidd o en nuestra lengua, más joven pero no por ello menos noble, \"el Lobo Blanco\". Geralt de Rivia es un personaje realmente excepcional. Un breve encuentro con él podría tentarnos a tacharlo de ser un mero espadachín, un simple cazador de monstruos, un tosco practicante de un sucio oficio, pero si lo miráis más de cerca pronto descubriréis que es un hombre de profundidades insondables, de puntos de vista únicos y con una gran experiencia que abarca todo el mundo. En la superficie, es introvertido, reservado y hasta podría decirse que gruñón, pero debajo hay un mar desbordante de bondad, un buen sentido del humor y una gran presteza en ayudar a sus amigos, ya sea con un buen consejo o blandiendo la espada magistralmente. Es un hombre de apariencia y modales bruscos y a veces desastrados, pero que sin embargo disfruta de una gran estima por parte del bello sexo. Es, por resumirlo, una contradicción andante.\n" +
                "Dejando de lado la falsa modestia, que tan incómoda me resulta, puedo decir que conozco su historia mejor que cualquier persona viva. He pasado con él por tiempos buenos y por tiempos difíciles, ayudándolo con un sabio consejo, palabras cálidas y un ingenio incisivo. Como resultado de ello, soy una parte vital de su historia, tanto en los episodios anteriores como en los presentes. Es por ello mi deber proseguir con mi crónica, y en beneficio de las generaciones futuras, poner por escrito el siguiente capítulo de sus gestas y hazañas.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Fgeralt2.jpg?alt=media&token=c0a69669-3990-4d5a-8aaa-68578bd52c47")
        val p2: Personaje= Personaje("Cirilla Fiona Elen Riannon","Bruja","Cintra",
            "Cirilla Fiona Elen Riannon, ¿qué puedo decir de ella? ¿Que el apócope de su nombre es Ciri, que nació en el 1251, que tiene el cabello ceniciento y una cicatriz en la mejilla?\n" +
                    "Todo es cierto, y propio de la Cirilla a quien mejor conozco, la que vi por primera vez hace tantos años, la que parecía... no corriente, pero sin duda no tan extraordinaria como es en realidad.\n" + "Porque Cirilla también es una bruja muy capacitada, heredera de varios tronos, la última portadora de la vieja sangre, una fuente poderosa y dotada de excepcionales talentos mágicos y la Dama del Espacio y el Tiempo. ¿Esto no hace que detalles como el color de su cabello o la fecha de su nacimiento resulten secundarios?\n" + "También podría deciros que es la hija adoptiva de Geralt, pero sería una simplificación flagrante. Ciri es mucho más. Es el destino de Geralt, su hija inesperada, alguien atada inseparablemente al brujo por los enmarañados grilletes del sino.\n" + "Cumpliendo con una tradición ancestral de los brujos, Geralt llevó a Ciri a Kaer Morhen cuando quedó a su cuidado. Allí, Vesemir y él le enseñaron las artes de los cazadores de monstruos profesionales. Fue entonces cuando se revelaron sus talentos mágicos y descubrieron que era una fuente. El don de Ciri también resultó ser una maldición, ya que la obligaría algún día a esconderse de todo el mundo... incluso de Geralt.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Fciri.jpg?alt=media&token=43a8bf8c-bedc-4532-949a-ae5ed5d363df")
        val p3:Personaje= Personaje("Triss Merigold","Hechizera","Temeria",
            "Triss Merigold de Maribor fue una legendaria hechicera temeria. Sus contemporáneos la llamaron \"Decimocuarta del Monte\" porque se pensó erróneamente que fue asesinada durante la Batalla del Monte de Sodden, pasando a la historia como Merigold la Intrépida. Miembro del Consejo Real del Rey Foltest junto con Fercart y Keira Metz, además de una de las miembros fundadoras de la Logia de Hechiceras, Triss estuvo involucrada en la política la mayor parte de su vida.\n" + "Amiga de Yennefer y del brujo Geralt, pero también infelizmente enamorada de este último. Triss se hizo cargo de Ciri en Kaer Morhen durante un tiempo y era como una hermana mayor para la muchacha. Fue a través de su intervención que Ciri no fue sometida a cambios hormonales nocivos en Kaer Morhen, que la hubieran despojado de sus características de género.\n" + "Triss era conocida por su hermoso cabello castaño (en los videojuegos es pelirroja) y sus ojos (azules en los libros, verdes en los videojuegos). Era una experta curandera y llevaba consigo una gran variedad de pociones mágicas, pero nunca las usaba sobre sí misma ya que era alérgica a estas. Llevaba un amuleto de zafiro cubierto con plata.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Ftriss.PNG?alt=media&token=d82688a1-3341-4bc2-896c-f24213f181cb")
        val p4:Personaje= Personaje("Yennefer","Hechizera","Aedirn","Hacía unos buenos veinte años que el brujo conocía a la hechicera de cabellos negros como ala de cuervo. Su amistad y los sentimientos entre ambos habían nacido de una aventura en común en la que se había visto implicado un djinn que concedió un deseo a Geralt, deseo que entrelazó sus destinos indisolublemente. No obstante, desde entonces su relación había sido bastante tormentosa, rica en altibajos, crisis y rupturas. El amor de Geralt y Yennefer es la prueba irrefutable de la afirmación de que los contrarios se atraen.\n" + "Unos cuantos años atrás, tras la separación llena de aventuras para ambos, Geralt y Yennefer habían reanudado su relación. Su momento de reposo se vio interrumpido por la cacería salvaje, que se llevó cautiva a Yennefer. El brujo partió de inmediato a salvarla, pero perdió la memoria al hacerlo. Cuando la recobró finalmente, reemprendió en el acto la misión de encontrar a su amada hechicera.\n" + "Después de dos años, el reencuentro de Geralt con Yennefer fue bastante distinto de lo que este había imaginado. No solo la hechicera estaba sana y salva, sino que además se había procurado la ayuda de un aliado inesperado y poderoso: el Imperio Nilfgaardiano.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Fyeneffer2.png?alt=media&token=1076682c-d92c-4303-8058-fb22cd574f14")
        val p5:Personaje= Personaje("Julian Alfred Pankratz","Bardo","Redania","Jaskier conoció a Geralt por primera vez en una fiesta en la ciudad de Guleta en Aedirn. Allí, el poeta había intentado seducir a una chica bajo el estrado de los músicos, y sus cuatro hermanos robustos lo estaban buscando por toda la ciudad, amenazando con castrarlo y cubrirlo con serrín y alquitrán.\n" + "El llamado Valle de las Flores parecía justo el lugar correcto para la fuga rápida del dúo, ya que se suponía que era el confín del mundo habitado. Fue en la pequeña ciudad de Posada de Arriba, ubicada en una parte de los Reinos del Norte que más tarde se convirtió en Dol Blathanna, donde el par tuvo su primera aventura juntos, involucrando a un silvano y un encuentro con los habitantes nativos de Dol Blathanna, los elfos. Durante esta aventura, Jaskier recibió su laúd invaluable de manos de Toruviel.\n" + "En algún momento, Jaskier ofreció sus servicios al Servicio Secreto de Redania, aunque parecía que su lealtad era bastante dudosa, ya que también colaboró con agentes temerios y fuerzas especiales.\n" + "Durante sus viajes con Geralt, Jaskier comenzó a escribir sus memorias, tituladas Medio siglo de poesía; dos veces, de hecho. Su primer intento se perdió en el fondo del armario de la duquesa de Toussaint después de que el poeta fuera desterrado de su ducado. Pero en lugar de lamentar esa pérdida, el poeta decidió reescribir sus memorias desde cero.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Fjaskier.png?alt=media&token=4d0c1302-dca4-4069-b00c-aa98ac799363")
        val p6:Personaje= Personaje("Eredin Bréacc Glas","Rey de la Cacería Salvaje","Tir Ná Lia","El nombre del rey de la cacería salvaje, la identidad del señor de las pesadillas, el ser oculto tras la máscara terrorífica... todo esto se desconocía.\n" + "La cacería salvaje era en realidad una brigada de caballería de élite del mundo de los Aen Elle, la gente de los alisos, comandada por su ambicioso e implacable rey, Eredin Bréacc Glas. El objetivo actual de su cacería era Cirilla, cuyo poder quería dominar para sacarle partido. El único obstáculo en su camino: Geralt de Rivia.\n" + "Ciri pudo arrojar algo de luz sobre las motivaciones del comandante de la cacería salvaje. La amenaza de la aniquilación pendía sobre la tierra de los Aen Elle. Eredin, de naturaleza belicosa y conquistadora, decidió resolver el problema de la manera más sencilla: tomando nuestro mundo. ¿Y cuál era la clave? El poder de Ciri, que le permitiría abrir las puertas a una invasión a gran escala.\n" + "Confiando en la potencia de su magia y en la habilidad de sus jinetes, Eredin lanzó un ataque frontal contra Kaer Morhen. Pese a los nobles sacrificios de los defensores, estuvo a punto de lograr la victoria. Solo el poder desencadenado de Ciri obligó a Eredin a retroceder. \n" + "El cruel rey de la cacería parecía imparable y destrozaba a todo aquel que se interponía en su camino... hasta que ese camino le llevó hasta Geralt de Rivia. Los dos expertos combatientes se enfrentaron en la última escaramuza en la fantasmal cubierta del Naglfar. La lucha fue larga y difícil, pero la espada del brujo encontró su objetivo y acabó con los sueños de poder y conquista de Eredin. Así murió Eredin Bréacc Glas, rey de la cacería salvaje.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Feredin.png?alt=media&token=177d2413-2db1-40e7-95b7-01db751f3bb4")
        val p7:Personaje=Personaje("Imlerith","General de la Cacería Salvaje","Tir Ná Lia","Imlerith, comandante de la cacería salvaje y presencia habitual en las pesadillas de Geralt, llevaba mucho tiempo persiguiendo a Ciri con la intención de entregársela a su soberano, Eredin. Este guerrero poderoso y brutal había librado innumerables batallas y campañas de los Aen Elle para conquistar otros mundos. Valoraba el enfrentamiento físico por encima de todo lo demás, con preferencia por las refriegas directas y sangrientas en las que los rivales tenían que demostrar su fuerza, agilidad y enfrentamiento en un combate a vida o muerte.\n" + "Imlerith atacó Kaer Morhen con el resto de la cacería. Los defensores de la fortaleza presenciaron horrorizados el peligroso poder de este guerrero. Vesemir, que se había pasado gran parte de su larga vida con una espada en la mano, se enfrentó heroicamente a este enemigo pero, por desgracia, fue vencido tras un enfrentamiento intenso y sangriento, pereciendo a manos del monstruo.\n" + "Sea cual sea su raza o estirpe, muchos guerreros comparten los mismos deseos y deleites. Imlerith no era una excepción: Avallac'h informó a Ciri de que el comandante solía abandonarse a los placeres carnales, y que aprovecharía su estancia en nuestro mundo para asistir al aquelarre de las moiras.\n" + "Geralt y Ciri decidieron ir allí para retarlo a un combate final. Geralt resultó victorioso, mató a Imlerith y vengó así la muerte de su maestro Vesemir.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Fimlerith.png?alt=media&token=c1e51497-0714-49e5-a179-cc3e1e678556")
        val p8:Personaje=Personaje("Caranthir","Navegador de la Cacería Salvaje","Tir Ná Lia","Caranthir es un producto del intento de reproducción selectiva de Avallac'h entre parejas élficas dotadas con la capacidad para manipular el tiempo y el espacio. A pesar del talento que poseía, se convirtió en un criminal y se unió a Eredin en la cacería salvaje. Según Avallac'h, a pesar de la indiferencia de Eredin hacia Caranthir, lo terminó reclutando después de pasar las pruebas que le preparó. Descrito por Ciri como \"reservado y pragmático\", una de las notas encontradas en el laboratorio de Avallac'h sugieren que también tenía un \"temperamento imprudente\", una \"tendencia a tomar riesgos tontos\", además de sentir cierto orgullo debido a sus capacidades.\n" + "Durante la búsqueda de Ciri, Caranthir exploró el escondite de Avallac'h. Más tarde participó en la batalla en Kaer Morhen, donde se batió en duelo contra Eskel, casi matando al brujo, hasta que Ciri logró detenerlo. Después de que Imlerith mató a Vesemir, Ciri desató sus poderes mágicos, matando a todos los que se encontraban en el área afectada. Caranthir abrió un portal para retirarse de Kaer Morhen y arrastró a su rey a través de él.\n" + "Cuando la cacería salvaje fue atraída hacia Undvik, Caranthir usó su magia para congelar a Geralt. Ciri se enfrentó al general élfico y pudo romper su bastón, permitiendo que Geralt se liberara del hielo. Caranthir intentó secuestrar a Ciri, aparentemente inconsciente, pero esta logró teletransportarse y Caranthir terminó enfrentando a Geralt. El brujo empaló al navegador, pero antes de que pudiera morir agarró a Geralt y lo teletransportó hacia las profundidades del mar, donde Caranthir continuó desangrándose, hundiéndose hacia su muerte. Geralt nadó hasta la superficie y sobrevivió.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Fcaranthir.png?alt=media&token=c47db7e8-1ece-41ff-8154-37beb4323dd8")
        val p9:Personaje=Personaje("Zoltan Chivay","Oficial de la Compañia de Zoltan Chivay","Mahakam","Enano, mercenario, veterano de Brenna, optimista incansable, altruista convencido, amante de las bebidas fuertes y de las canciones descaradas, experto en el juego del gwynt y, por encima de todo, un querido y fiel amigo de Geralt y mío. Damas y caballeros, quiero presentaros a Zoltan Chivay. Nos hicimos amigos rápidamente hace muchos años, cruzando un Riverdell devastado por la guerra, cuando Geralt y yo nos lo encontramos con la banda que dirigía en aquel momento.\n" + "Después, el destino volvió a reunirnos en muchas ocasiones y terminamos siendo compañeros inseparables para lo bueno y lo malo. Al comienzo de nuestro relato, Zoltan y yo nos habíamos hecho socios y llevábamos juntos una taberna de Novigrado: el Romero y Tomillo.\n" + "Al salvarme del vehículo que me conducía a mi muerte, Zoltan volvió a demostrarme que nunca abandonaría a un amigo en apuros. Y pronto sería él quien recibiría ayuda: para recuperarse de un revés económico, aceptó un préstamo de un jefe de la mafia de Novigrado, ganándose así varios y desafortunados enemigos.\n" + "Pensaba pagar su deuda reuniendo una valiosa colección de cartas de gwynt, empresa arriesgada teniendo en cuenta que, en aquella época, los círculos de gwynt de Novigrado estaban frecuentados por peligrosos asesinos. Nunca lo habría conseguido sin la ayuda de Geralt.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Fzoltan.png?alt=media&token=9b75b52f-dd3f-4b5c-8b45-9b1ffde52658")
        val p10:Personaje= Personaje("Emhyr Van Emreis","Emperador de Nilgaard","Nilgard","Pocos nombres en la historia del continente producían tanto respeto y terror como el de Emhyr var Emreis, Deithwen Addan yn Carn aerp Morvudd - la Llama Blanca que Baila sobre los Túmulos de sus Enemigos-, emperador de Nilfgaard, señor de Metinna, de Ebbing y de Gemmera, soberano de Nazair y Vicovaro, que gobernaba la mitad del mundo civilizado y aspiraba a conquistar la otra mitad. Era uno de esos personajes cuyas gestas y hazañas conformaban el destino de reinos enteros y de sus pueblos. ¿Que podría entonces querer de un simple brujo?\n" + "El emperador expuso clara y sucintamente lo que quería. Su hija, la protegida de Geralt, corría un gran peligro, ya que la Cacería salvaje la perseguía. El brujo, un rastreador soberbio unido a la hija de Emhyr por los férreos lazos del destino, tenía muchas más posibilidades que nadie en el mundo de dar con ella.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Femhyr.png?alt=media&token=ab03fba9-7ed1-4f8c-84ab-46327f8e320d")
        val p11:Personaje= Personaje("Vernon Roche","Comandante del ejecercito temerio","Temeria","Como comandante de las fuerzas especiales temerias, un escuadrón de élite conocido como los Franjas Azules, Vernon Roche había sido uno de los subordinados de confianza del rey Foltest. Una y otra vez, Roche se mostraba leal, eficaz y muy profesional. Pocos demostraban tanta habilidad al aplacar rebeliones, luchar contra los nilfgaardianos o liquidar bandas de scoia'tael. Pero cuando comenzó nuestra historia, había perdido a su rey, sus hombres y su tierra, por lo que decidió comenzar una guerra de guerrillas contra las fuerzas ocupantes, abrumadoramente más poderosas.\n" + "La guerra de guerrillas de Roche dependía de la ayuda redaniana, aunque estaba claro que trabajar con Radovid no era de su gusto.\n" + "Algo más tarde se descubrió que Vernon se había unido a una conspiración para asesinar a Radovid. Era consciente de que, una vez terminada la guerra, aquel rey loco acabaría con cualquier esperanza de una Temeria libre, y el mismo Roche se convertiría en un lastre y un enemigo potencial.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Fvernon.png?alt=media&token=8f409034-44b5-4d66-a5b1-c8da5256a588")
        val p12:Personaje= Personaje("Foltest","Rey de Temeria","Temeria",
            "En retrospectiva, su majestad Foltest fue sin duda un personaje excepcional si lo comparamos con otras testas coronadas. El rey de Temeria, príncipe de Sodden, soberano del Pontar y Mahakam y protector de alto nivel de Brugge, Angren, Riverdell y Ellander era un monarca firme y decidido. El tipo de hombre que cuando recibía un golpe, sonaba como si estuviera forjado de acero, no de cagarrutas. Al ser soltero, tenía una vida privada un tanto informal. En su juventud, cuando aún era príncipe, Foltest dio prueba de lo que podía hacer, que era mucho. Todo el mundo conoce la historia de amor con su propia hermana y el fruto de aquella relación, su hija Adda, asi como su posterior apego por la baronesa Marie Louise La Valette. Ambas relaciones le acarrearon, por así decirlo, graves consecuencias y, una vez más, Geralt quedó atrapado en mitad del embrollo resultante.\n" + "Foltest seguía sintiendo algo por su antigua amante, y quería salvar a sus hijos nacidos fuera del matrimonio. De lo contrario, se convertirían en una baza en maniobras políticas. Y cuando Foltest hubo tomado una decisión, nada ni nadie pudieron interponerse en su camino.\n" + "La muerte de los grandes y poderosos de este mundo no siempre va acorde con sus vidas. El asesinato fue tan repentino que ni siquiera el brujo pudo reaccionar a tiempo. La hoja de una daga le rebanó el pescuezo a Foltest, rey de Temeria, y derramó sangre en el suelo de la ermita del castillo. Así moría uno de los reyes más poderosos del Norte a manos de un asesino con ropas de monje.","https://firebasestorage.googleapis.com/v0/b/thewitcher-54c99.appspot.com/o/the%20witcher%2Ffoltest.png?alt=media&token=f40d4abb-ecb4-4efa-b21a-9b793af02573")
        listaPersonajes.add(p1)
        listaPersonajes.add(p2)
        listaPersonajes.add(p3)
        listaPersonajes.add(p4)
        listaPersonajes.add(p5)
        listaPersonajes.add(p6)
        listaPersonajes.add(p7)
        listaPersonajes.add(p8)
        listaPersonajes.add(p9)
        listaPersonajes.add(p10)
        listaPersonajes.add(p11)
        listaPersonajes.add(p12)
    }

    fun getListaPersonajes():List<Personaje>{
        return listaPersonajes
    }
}
